# Generated by Django 3.2 on 2021-06-15 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_out', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('revenue_in', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('stock_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('phone_number', models.DecimalField(decimal_places=0, max_digits=10)),
                ('vat_number', models.DecimalField(decimal_places=0, max_digits=15)),
                ('pan_number', models.DecimalField(decimal_places=0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Importer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('owner_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('phone_number', models.DecimalField(decimal_places=0, max_digits=10)),
                ('vat_number', models.DecimalField(decimal_places=0, max_digits=15)),
                ('pan_number', models.DecimalField(decimal_places=0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(max_length=30)),
                ('model_name', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='sale_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.item')),
            ],
        ),
        migrations.CreateModel(
            name='stock_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.BooleanField(default=True)),
                ('quantity', models.PositiveIntegerField()),
                ('in_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.item')),
            ],
        ),
        migrations.CreateModel(
            name='stock_total',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('importer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.importer')),
                ('items', models.ManyToManyField(to='mainapp.stock_item')),
            ],
        ),
        migrations.CreateModel(
            name='sale_total',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.customer')),
                ('items', models.ManyToManyField(to='mainapp.sale_item')),
            ],
        ),
    ]
