# Generated by Django 3.2 on 2021-07-15 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('expense_out', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('revenue_in', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stock_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('owner_name', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=50)),
                ('phone_number', models.DecimalField(decimal_places=0, max_digits=10)),
                ('vat_number', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('pan_number', models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True)),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('total_credit', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Importer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('owner_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('phone_number', models.DecimalField(decimal_places=0, max_digits=10)),
                ('vat_number', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('pan_number', models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True)),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('total_credit', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(default='none', max_length=50, null=True)),
                ('company_name', models.CharField(default='none', max_length=50, null=True)),
                ('size', models.CharField(blank=True, max_length=30, null=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_stock', models.BooleanField(default=False)),
                ('total_in_quantity', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Item_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='sale_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.BooleanField(default=True)),
                ('quantity', models.PositiveIntegerField()),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.item')),
            ],
        ),
        migrations.CreateModel(
            name='stock_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.BooleanField(default=True)),
                ('quantity', models.PositiveIntegerField()),
                ('in_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.item')),
            ],
        ),
        migrations.CreateModel(
            name='stock_total',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateField(auto_now_add=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_paid', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('credit', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('importer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.importer')),
                ('items', models.ManyToManyField(to='mainapp.stock_item')),
            ],
        ),
        migrations.CreateModel(
            name='sale_total',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold_at', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_paid', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('credit', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.customer')),
                ('items', models.ManyToManyField(to='mainapp.sale_item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.item_type'),
        ),
    ]
