# Generated by Django 3.2 on 2021-06-06 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('phone_number', models.DecimalField(decimal_places=0, max_digits=10)),
                ('vat_number', models.DecimalField(decimal_places=0, max_digits=15)),
                ('pan_number', models.DecimalField(decimal_places=0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Importer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('owner_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('phone_number', models.DecimalField(decimal_places=0, max_digits=10)),
                ('vat_number', models.DecimalField(decimal_places=0, max_digits=15)),
                ('pan_number', models.DecimalField(decimal_places=0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='ItemClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='sale_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('sold_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='stock_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('itemclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.itemclass')),
                ('model_name', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField(max_length=100)),
            ],
            bases=('mainapp.itemclass',),
        ),
        migrations.CreateModel(
            name='stock_total',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.importer')),
                ('items', models.ManyToManyField(to='mainapp.stock_item')),
            ],
        ),
        migrations.CreateModel(
            name='sale_total',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ManyToManyField(to='mainapp.sale_item')),
            ],
        ),
        migrations.AddField(
            model_name='stock_item',
            name='items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.item'),
        ),
        migrations.AddField(
            model_name='sale_item',
            name='items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.item'),
        ),
    ]
