# Generated by Django 3.2 on 2021-06-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_stock',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
