# Generated by Django 3.2.5 on 2021-07-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_sale_total_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale_total',
            name='sold_at',
            field=models.DateField(),
        ),
    ]
