# Generated by Django 3.2 on 2021-06-13 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_stock_item_current1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock_item',
            name='current1',
        ),
    ]
