# Generated by Django 3.2 on 2021-07-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210711_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='total_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='customer',
            name='total_credit',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='importer',
            name='total_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='importer',
            name='total_credit',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='sale_total',
            name='credit',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='sale_total',
            name='total_paid',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='stock_total',
            name='credit',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='stock_total',
            name='total_paid',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
    ]
