# Generated by Django 3.2 on 2021-06-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_remove_stock_item_current1'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_item',
            name='in_price',
            field=models.DecimalField(decimal_places=2, default=600, max_digits=8),
            preserve_default=False,
        ),
    ]
