# Generated by Django 3.2.5 on 2021-07-19 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20210720_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale_total',
            name='sold_at',
        ),
    ]
