# Generated by Django 3.2 on 2021-08-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_remove_sale_total_sold_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale_total',
            name='sold_att',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
