# Generated by Django 3.2 on 2021-08-09 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_sale_total_profit'),
        ('mainapp', '0008_remove_sale_total_sold_at'),
    ]

    operations = [
    ]
