# Generated by Django 3.2 on 2021-08-10 14:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_alter_sale_total_sold_att'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale_total',
            name='sold_att',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
