# Generated by Django 4.0.4 on 2022-04-23 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_return_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='return_item',
        ),
    ]
